
const Screens = Object.freeze({
  HOME: 'HOME',
  WRITE_CARDS: 'WRITE_CARDS',
  START_TURN: 'START_TURN',
  GUESSING: 'GUESSING',
  FINISHED_BOWL: 'FINISHED_BOWL',
  FINSIHED_LAST_BOWL: 'FINSIHED_LAST_BOWL',
  GAME_OVER: 'GAME_OVER',
})

export default Screens
